# Generated by Django 5.2.7 on 2025-10-12 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core1', '0002_usuario_delete_persona'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Usuario',
            new_name='Persona',
        ),
    ]
