# Generated by Django 5.2.7 on 2025-10-12 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core1', '0003_rename_usuario_persona'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='cedula',
            field=models.CharField(max_length=20),
        ),
    ]
