# Generated by Django 5.2.7 on 2025-10-12 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core1', '0004_alter_persona_cedula'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('salario_base', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
