# Generated by Django 5.2.7 on 2025-10-12 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core1', '0006_remove_persona_estado_remove_persona_mensaje_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='correo',
            field=models.EmailField(max_length=254),
        ),
    ]
