# Generated by Django 5.2.7 on 2025-11-06 18:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core1', '0007_alter_persona_correo'),
        ('core2', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionNomina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('porcentaje_seguridad_social', models.DecimalField(decimal_places=2, default=4.0, max_digits=5)),
                ('porcentaje_salud', models.DecimalField(decimal_places=2, default=4.0, max_digits=5)),
                ('porcentaje_pension', models.DecimalField(decimal_places=2, default=4.0, max_digits=5)),
                ('valor_auxilio_transporte', models.DecimalField(decimal_places=2, default=140606, max_digits=10)),
                ('salario_minimo_legal', models.DecimalField(decimal_places=2, default=1300000, max_digits=10)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Configuración de Nómina',
                'verbose_name_plural': 'Configuraciones de Nómina',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='ProcesoContratacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_proceso', models.CharField(choices=[('EN_REVISION', 'En Revisión'), ('APROBADO', 'Aprobado para Contratación'), ('RECHAZADO', 'Rechazado'), ('CONTRATADO', 'Contratado')], default='EN_REVISION', max_length=20)),
                ('fecha_revision', models.DateTimeField(auto_now_add=True)),
                ('fecha_decision', models.DateTimeField(blank=True, null=True)),
                ('observaciones_rrhh', models.TextField(blank=True)),
                ('empleado_creado', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proceso_origen', to='core2.empleado')),
                ('revisado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procesos_revisados', to=settings.AUTH_USER_MODEL)),
                ('solicitud', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='proceso_contratacion', to='core1.solicitud')),
            ],
            options={
                'verbose_name': 'Proceso de Contratación',
                'verbose_name_plural': 'Procesos de Contratación',
                'ordering': ['-fecha_revision'],
            },
        ),
    ]
